### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by factorioplayer1** [urda/quick-start-delight#9]
Error while running event quick-start-delight::on_player_created (ID 27) __quick-start-delight__/qsd/utils.lua:43: attempt to index local 'new_gear' (a nil value) stack traceback: 	__quick-start-delight__/qsd/utils.lua:43: in function 'configure_gear' 	__quick-start-delight__/control.lua:60: in function <__quick-start-delight__/control.lua:20>

tried starting just this mod alone with Space age ones and it vomits that Ver 2.0.7 , latest of the Mod

**Comment by urda** [comment]
I fixed a few bugs the latest version of the mod is `2.1.2` please update your mod. See also #3 .

**Comment by urda** [comment]
@factorioplayer1 I've tested the latest version of this mod `2.1.2` by-itself, in both *Base Game* and *Space Age*. You can see it here https://github.com/urda/quick-start-delight/pull/5#issuecomment-2428685823

If you still have a crash after making sure you are on the latest version of `quick-start-delight`, please list all your mods in use, and a screenshot of the game crash.

**Comment by factorioplayer1** [comment]
i have the latest Version of the Mod i looked to see if it had a update , then quit and started factorio and check to see if a update was there and isnt , and it crashed with the same error once i tried to play , as soon as the Map loaded it crashed and went back the Menu screen

**Comment by urda** [comment]
Make sure you have the latest version of factorio `2.0.8` and are using the `quick-start-delight` release `2.1.2`  because it appears to be working for:

- base game here: https://github.com/urda/quick-start-delight/pull/5#issuecomment-2428685823
- space age here: https://github.com/urda/quick-start-delight/pull/5#issuecomment-2428693230

Please make sure you have installed the right versions, and try with a new map if necessary.
